ALTER TABLE place ADD COLUMN city VARCHAR(255);
ALTER TABLE place ADD COLUMN state VARCHAR(2);
ALTER TABLE place ADD COLUMN country VARCHAR(255);
ALTER TABLE place ADD COLUMN street VARCHAR(255);
ALTER TABLE place ADD COLUMN house_number VARCHAR(255);
ALTER TABLE place ADD COLUMN neighborhood VARCHAR(255);